[server]
port = 8080
secret = "change_this_to_anything_random"

[database]
type = "sqlite"
url = "file:database.db"

[frontend]
enabled = true

[search]
enabled = true

[proxy]
enabled = true

[api]
enabled = true

[admin]
enabled = false

[security]
rate_limit = false
